// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3j6EbYxEQlYj7lE0zzVVz1iCoseEm2PY',
    appId: '1:166329730289:web:322c77e4cd8a8211e1d550',
    messagingSenderId: '166329730289',
    projectId: 'briannamutali-ab58f',
    authDomain: 'briannamutali-ab58f.firebaseapp.com',
    storageBucket: 'briannamutali-ab58f.appspot.com',
    measurementId: 'G-TB4FJWLGJ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyaotMX7vhOUn3bFAWKLIIzzXARM5fv7U',
    appId: '1:166329730289:android:99104f524594108ae1d550',
    messagingSenderId: '166329730289',
    projectId: 'briannamutali-ab58f',
    storageBucket: 'briannamutali-ab58f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZeaZtVRRv808IwVBjut-znRJOeVPWo_c',
    appId: '1:166329730289:ios:ebfc5d8438e0b88de1d550',
    messagingSenderId: '166329730289',
    projectId: 'briannamutali-ab58f',
    storageBucket: 'briannamutali-ab58f.appspot.com',
    iosClientId: '166329730289-sn59k7pg98srum92cif4uh58vbkecbaa.apps.googleusercontent.com',
    iosBundleId: 'com.briannamutali.briannamutali',
  );
}
